config/routes.rb
AppForBands::Application.routes.draw do
  get "pages/index"

  get "pages/contact", as: "contact"

  get "pages/about", as: "about"

  match "terms-and-conditions" => "pages#terms", as:"terms"

  get "welcome/index"
  get "welcome/home"
  
  resources :bands

  root :to => 'pages#index'

end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :desription, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bands }
    end
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
    @band = Band.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @band }
    end
  end

  # GET /bands/new
  # GET /bands/new.json
  def new
    @band = Band.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @band }
    end
  end

  # GET /bands/1/edit
  def edit
    @band = Band.find(params[:id])
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(params[:band])

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render json: @band, status: :created, location: @band }
      else
        format.html { render action: "new" }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bands/1
  # PUT /bands/1.json
  def update
    @band = Band.find(params[:id])

    respond_to do |format|
      if @band.update_attributes(params[:band])
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band = Band.find(params[:id])
    @band.destroy

    respond_to do |format|
      format.html { redirect_to bands_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #get/pages/index
  def index
		  	
  end


  #get/pages/contact
  def contact

  end


  #get/pages/about
  def about
  end


  #get/pages/terms
  def terms
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def home
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desription %><br />
    <%= f.text_field :desription %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
    
      

    <% @bands.each do |band| %>
      <div class="post">
        <h2>
        <%= band.name %>
        </h2>
        <div class="meta">
          Posted on:
          <%= band.created_at.strftime("%F,%T") %>
        </div>
        <div class="content">
          <%= band.desription %>
          <p>
            <%= link_to "Citeste mai mult", band%>
          </p>
        </div>

        <div class="actions">

          <%= link_to 'Edit', edit_band_path(band) %>
          <%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    <% end %>

    <br />

    <%= link_to 'New Band', new_band_path %>

  

app/views/bands/new.html.erb
<h1>New band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @band.name %>
</p>

<p>
  <b>Desription:</b>
  <%= @band.desription %>
</p>


<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppForBands</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="span12">
				<h1>
					Band Blog
				</h1>
			</div>
		</div>
		<nav>
			
				<%= render partial: "shared/menu"%>
			
		</nav>
		<div class="row">
			<div class="span9">
				<%= yield %>
			</div>
			<div class="span3">
				<%= render partial: "shared/sidebar"%>
			</div>
		</div>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
this is homepage

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/shared/_menu.html.erb
<ul class="nav nav-pills">
	<li>
		
		<%= link_to "Home", root_path%>
	</li>
	<li>
		
		<%= link_to "Bands", bands_path%>
	</li>
	<li>
		<%= link_to "Contact", contact_path%>
	</li>
	<li>
		<%= link_to "Terms", terms_path%>
	</li>
	<li>
		<%= link_to "About us", about_path%>
	</li>

</ul>

app/views/shared/_sidebar.html.erb
<div class="span3">
	<h3>Side bar</h3>
	<p>blblslsbllslfsldflsldfblsdlfgldsfgldsfg</p>
</div>

app/views/welcome/home.html.erb
<h1>This is home page</h1>
<a href="#">Link</a>

app/views/welcome/index.html.erb
<h1>Hello I love coffee :D</h1>
<a href="">Link</a>